logger:
  name: mlxp.DefaultLogger
  parent_log_dir: ./logs
  forced_log_id: -1
  log_streams_to_file: false
version_manager:
  name: mlxp.GitVM
  parent_work_dir: ./.work_dir
  compute_requirements: false
use_version_manager: false
use_scheduler: false
use_logger: true
interactive_mode: true
resolve: true
as_ConfigDict: true
