seed: 0
dataset:
  _target_: tasks.mnist.data.build_mnist
  data_storage: "data"
  name: "mnist"
  download: True
  batch_size: 8
  num_workers: 4
  pin_memory: False
  n_train: 1500
  n_val: 1000

model:
  _target_: tasks.mnist.models.build_net

optimizer:
  _target_: optimizers.dog.gdog.build_gdog

averager:
  _target_: optimizers.averagers.build_pda

loss:
  _target_: tasks.losses.build_crossentropy

train:
  force_gpu: False
  epochs: 10
  eval_every_n_steps: 1
  compile: True
