seed: 0
dataset:
  _target_: tasks.simple_classification.data.build_moons
  num_workers: 4
  pin_memory: False
  batch_size: 8
  val_batch_size: 250
  n_train: 250
  n_val: 0
  train_only: True
  noise: 0.05
  seed: 0

model:
  _target_: tasks.simple_classification.models.build_MLP
  input_size: 2
  output_size: 2
  hidden_sizes: [16]

optimizer:
  _target_: optimizers.builtin.build_sgd
  learning_rate: 2.0e-2

averager: null

loss:
  _target_: tasks.losses.build_crossentropy

train:
  force_gpu: False
  epochs: 2000
  eval_every_n_steps: 1
  compile: False
  early_stopping_patience: 10
